[project]
name        = "WhereToLive.LA"
version     = "0.1.0"
description = "An interactive map of available rentals in Los Angeles County. Updated weekly."             
readme      = "README.md"
license     = {  } # 
requires-python = ">=3.11"

dependencies = [
  "beautifulsoup4~=4.14.3",
  "bleach~=6.3.0",
  "boto3~=1.42.21",
  "brotli~=1.2.0",
  "dash-bootstrap-components~=2.0.4",
  "dash-extensions~=2.0.4",
  "dash-leaflet~=1.1.3",
  "dash-mantine-components~=2.4.1",
  "dash~=3.3.0",
  "flask~=3.1.2",
  "geopandas~=1.1.2",
  "geopy~=2.4.1",
  "gevent~=25.9.1",
  "gunicorn~=23.0.0",
  "imagekitio~=5.0.0",
  "loguru~=0.7.3",
  "numpy~=2.4.0",
  "openpyxl~=3.1.5",
  "orjson~=3.11.5",
  "pandas~=2.3.3",
  "protobuf~=6.33.2",
  "pyarrow~=22.0.0",
  "python-dotenv~=1.2.1",
  "pyyaml",               # unpinned, take latest
  "requests~=2.32.5",
  "tables",               # unpinned, take latest
  "pytest",
  "user-agents~=2.2.0",
]

[project.optional-dependencies]
dev = [
  "pytest>=8.0.0",
]
