[project]
name        = "WhereToLive.LA"
version     = "1.0.0"
description = "An interactive map of available rentals in Los Angeles County. Updated weekly."             
readme      = "README.md"
license     = {  } # 
requires-python = ">=3.11"

dependencies = [
  "beautifulsoup4~=4.14.3",
  "bleach~=6.3.0",
  "boto3~=1.42.34",
  "brotli~=1.2.0",
  "dash-bootstrap-components~=2.0.4",
  "dash-extensions~=2.0.4",
  "dash-leaflet~=1.1.3",
  "dash-mantine-components~=2.5.0",
  "dash~=3.4.0",
  "flask~=3.1.2",
  "geopandas~=1.1.2",
  "geopy~=2.4.1",
  "gevent~=25.9.1",
  "gunicorn~=24.1.1",
  "imagekitio==4.2.0",
  "loguru~=0.7.3",
  "numpy~=2.4.0",
  "openpyxl~=3.1.5",
  "orjson~=3.11.5",
  "pandas~=3.0.0",
  "protobuf~=6.33.2",
  "pyarrow~=23.0.0",
  "python-dotenv~=1.2.1",
  "pyyaml~=6.0.3",
  "requests~=2.32.5",
  "tables~=3.10.2",
  "pytest~=9.0.2",
  "user-agents~=2.2.0",
  "flask-compress>=1.23",
]

[project.optional-dependencies]
dev = [
  "pytest~=9.0.2",
]
